# SPDX-License-Identifier: GPL-2.0

dtbo-$(CONFIG_EXYNOS9810_N770F) += \
	exynos9810-r7_eur_open_00.dtbo \
	exynos9810-r7_eur_open_01.dtbo \
	exynos9810-r7_eur_open_02.dtbo \
	exynos9810-r7_eur_open_03.dtbo \
	exynos9810-r7_eur_open_04.dtbo \
	exynos9810-r7_eur_open_05.dtbo

always		:= $(dtbo-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtbo
